---
- hosts: wazuh-agents
  become: true
  become_user: root
  roles:
    - wazuh-ansible/roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: 10.0.0.13
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: "http"
        api_user: ansible
        max_retries: 5
        retry_interval: 5
